### ISSUE TITLE
I want to contribute to this project

### ISSUE THREAD

**Issue by eren-erver** [ofeksadlo/CSGO-Aimbot-CNN#2]
Hello , I have a pc that I don't use if you can send me the training file I can train the model with that pc.My pc is amd ryzen 3 1200 3.8ghz AMD Radeon RX 560 2gb

**Comment by eren-erver** [comment]
And one more thing , is it easy to implement tensorflow ?

**Comment by ofeksadlo** [comment]
First of all thank you for wanting to help.
The thing is I got all the computer power I need using google colab. Beyond that
I've used darknet to train my model which doesn't support AMD GPU so your
unused pc won't help in that case. 
If you want I can send you a link to the entire dataset then you can train it however you like.

About implementing it to tensorflow. I wouldn't say it's that difficult but more of hassle.
You'll need to convert your yolo model in order to inference it.
I've chose to just use the darknet port that OpenCV provide for this matter.
Because I don't think the result would be that much better infercing the model using tensorflow.
